/** ENUMS */
export enum TYPES {
  SELECTED_COUNTRY = "SELECTED_COUNTRY",
  UPDATE_CITIES = "UPDATE_CITIES ",
  UPDATE_AREAS = "UPDATE_AREAS",
  GET_COUNTRIES = "GET_COUNTRIES",
  COUNTRIES_LOADING = "COUNTRIES_LOADING",
}
